name: jappeos_desktop
description: Desktop environment for JappeOS.
publish_to: 'none'
version: 1.0.0+1
google_sign_in_web: ^0.9.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  #shadcn_flutter:
  #  git:
  #    url: https://github.com/JappeOS/shadcn_flutter.git
  #    ref: master

  shadcn_flutter:
    path: ../shadcn_flutter

  # TODO
  #jdwm_flutter:
  #  git:
  #    url: https://github.com/JappeOS/JDWM.git
  #    ref: main
  #    path: jdwm_flutter
  ### TODO
  jdwm_flutter:
    path: ../JDWM/jdwm_flutter

  jappeos_desktop_base:
    path: ../jappeos_desktop_base

  jappeos_services:
    git:
      url: https://github.com/JappeOS/jappeos_services.git
      ref: dev

  provider: ^6.0.3
  event: ^3.1.0
  highlight: ^0.7.0
  flutter_svg: ^2.0.6
  vector_math: ^2.1.4
  davinci: ^2.1.1
  http: ^1.0.0
  args: ^2.5.0
  intl: ^0.20.2
  widget_and_text_animator: ^1.1.5
  freedesktop_desktop_entry: ^0.6.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - resources/images/desktop/backgrounds/
    - resources/images/desktop/backgrounds/.private/
    - resources/images/null.png
    - resources/images/_icontheme/Default/apps/